CREATE OR REPLACE VIEW h_hmfo_fsi_dm.gd_rst_ing.unshipped_compat_v AS
WITH cm AS (
  SELECT
    *,
    LPAD(CAST(`고객코드` AS STRING), 10, '0') AS `고객코드10`
  FROM h_hmfo_fsi.gd_rst_ing.sap_zsdrxd03_customer_master_rst_ing_d
)
SELECT
  s.`구분`,
  s.`물류센터`,
  s.`물류센터명`,
  s.`플랜트`,
  s.`플랜트명`,
  s.`배치`,
  s.`출고일자`,
  s.`배송처코드`,
  s.`배송처명`,
  s.`통합배송처ID`,
  s.`통합배송처명`,
  s.`출고구분명`,
  s.`주문번호`,
  s.`주문순번`,
  s.`출고번호`,
  s.`순번`,
  s.`자재그룹`,
  s.`상품코드`,
  s.`상품명`,
  s.`SAP상품명`,
  s.`규격`,
  s.`SAP상품코드`,
  s.`상태명`,
  s.`이력관리구분명`,
  s.`TC상품구분명`,
  s.`상품온도구분`,
  s.`미출고사유`,
  s.`미출사유명`,
  s.`주문미출내용`,
  s.`귀책사유`,
  s.`피킹타입구분`,
  s.`차량번호`,
  s.`차량번호_FULL`,
  s.`운전자명`,
  s.`운전자연락처`,
  s.`부서코드`,
  s.`부서명`,
  s.`영업담당자명`,
  s.`영업담당자HP`,
  s.`공급처코드`,
  s.`공급처명`,
  s.`박스입수`,
  s.`예정수량`,
  s.`등록수량`,
  s.`출고수량`,
  s.`배송수량`,
  CAST(s.`총미출수량` AS DOUBLE) AS `미출수량`,
  s.`총예정량`,
  s.`총등록량`,
  s.`총출고수량`,
  s.`총배송수량`,
  s.`총미출수량`,
  s.`update_date`,
  s.`file_name`,
  s.`통합배송처명` AS `거래처명`,
  s.`상품명` AS `자재명`,
  CAST(s.`총미출수량` AS DOUBLE) AS `미출고수량`,
  s.`출고일자` AS `주문일자`,
  LPAD(COALESCE(NULLIF(c.`FC본부`, ''), s.`통합배송처ID`), 10, '0') AS `ZC본부`,
  COALESCE(NULLIF(TRIM(c.`FC본부명`), ''), s.`통합배송처명`) AS `ZC본부명`
FROM h_hmfo_fsi.gd_fsi_ent.helo_periodic_unshipped_hist_f s
LEFT JOIN cm c
  ON LPAD(CAST(s.`통합배송처ID` AS STRING), 10, '0') = c.`고객코드10`
