CREATE OR REPLACE VIEW h_hmfo_fsi_dm.gd_rst_ing.chatbot_sales_custmasters_compat_v AS
WITH cm AS (
  SELECT
    *,
    LPAD(CAST(`고객코드` AS STRING), 10, '0') AS `고객코드10`
  FROM h_hmfo_fsi.gd_rst_ing.sap_zsdrxd03_customer_master_rst_ing_d
)
SELECT
  CAST(NULL AS STRING) AS `클라이언트`,
  date_format(s.`대금청구일`, 'yyyy') AS `년도`,
  date_format(s.`대금청구일`, 'yyyyMM') AS `년월`,
  date_format(s.`대금청구일`, 'yyyyMMdd') AS `대금청구일`,
  '20' AS `사업부`,
  '외식식재사업부' AS `사업부명`,
  s.`부서코드` AS `부서`,
  s.`부서명` AS `부서명`,
  s.`지점코드` AS `지점`,
  s.`지점명` AS `지점명`,
  CAST(NULL AS STRING) AS `지점그룹`,
  CAST(NULL AS STRING) AS `지점그룹명`,
  LPAD(COALESCE(NULLIF(c.`ZA대표거래처`, ''), s.`고객코드`), 10, '0') AS `ZA거래처`,
  COALESCE(za.`고객명`, s.`고객명`) AS `ZA거래처명`,
  LPAD(COALESCE(NULLIF(c.`ZB본부`, ''), s.`고객코드`), 10, '0') AS `ZB본지점`,
  COALESCE(zb.`고객명`, s.`고객명`) AS `ZB본지점명`,
  LPAD(COALESCE(NULLIF(c.`ZP본사`, ''), s.`고객코드`), 10, '0') AS `ZP대표고객`,
  COALESCE(zp.`고객명`, s.`고객명`) AS `ZP대표고객명`,
  c.`사원번호` AS `영업사원`,
  c.`영업사원명` AS `영업사원명`,
  LPAD(CAST(s.`고객코드` AS STRING), 10, '0') AS `거래처`,
  s.`고객명` AS `거래처명`,
  CAST(NULL AS STRING) AS `판매문서유형`,
  s.`상품코드` AS `자재`,
  s.`상품명` AS `자재명`,
  CAST(NULL AS STRING) AS `자재유형`,
  CAST(NULL AS STRING) AS `자재유형명`,
  CAST(NULL AS STRING) AS `자재그룹`,
  CAST(NULL AS STRING) AS `자재그룹명`,
  c.`납품센터` AS `플랜트`,
  c.`납품센터명` AS `플랜트명`,
  CAST(NULL AS STRING) AS `MD`,
  CAST(NULL AS STRING) AS `MD명`,
  CAST(NULL AS STRING) AS `팀`,
  CAST(NULL AS STRING) AS `팀명`,
  CAST(NULL AS STRING) AS `자재계층1`,
  CAST(NULL AS STRING) AS `자재계층1명`,
  CAST(NULL AS STRING) AS `자재계층2`,
  CAST(NULL AS STRING) AS `자재계층2명`,
  CAST(NULL AS STRING) AS `자재계층3`,
  CAST(NULL AS STRING) AS `자재계층3명`,
  CAST(NULL AS STRING) AS `자재계층4`,
  CAST(NULL AS STRING) AS `자재계층4명`,
  CAST(NULL AS STRING) AS `경로`,
  CAST(NULL AS STRING) AS `경로명`,
  c.`고객계정그룹` AS `고객계정`,
  c.`개설사원` AS `개설사원`,
  CAST(NULL AS STRING) AS `개설사원명`,
  CAST(NULL AS STRING) AS `공급업체번호`,
  CAST(NULL AS STRING) AS `공급업체명`,
  CAST(s.`정가` / 100 AS DECIMAL(38,18)) AS `매출액`,
  CAST(s.`매출원가` / 100 AS DECIMAL(38,18)) AS `매출원가`,
  CAST(s.`수량` AS DECIMAL(38,18)) AS `매출수량`,
  CAST(s.`평균단가` / 100 AS DECIMAL(38,18)) AS `단가`,
  s.`단위` AS `단위`,
  CAST(NULL AS STRING) AS `통화`,
  CAST(NULL AS STRING) AS `배송구분`,
  LPAD(COALESCE(NULLIF(c.`FC본부`, ''), NULLIF(c.`ZP본사`, ''), s.`고객코드`), 10, '0') AS `ZC본부`,
  CAST('' AS STRING) AS `ZC본부명`,
  c.`1레벨` AS `고객계층1`,
  c.`2레벨` AS `고객계층2`,
  c.`3레벨` AS `고객계층3`,
  c.`1레벨명` AS `고객계층1명`,
  c.`2레벨명` AS `고객계층2명`,
  c.`3레벨명` AS `고객계층3명`,
  CAST(NULL AS STRING) AS `TYPET`,
  CAST(NULL AS DECIMAL(38,18)) AS `매출원가CO`,
  CAST(NULL AS DECIMAL(38,18)) AS `확정_입고총계`,
  CAST(NULL AS DECIMAL(38,18)) AS `확정_원가총계`,
  c.`사업자번호` AS `사업자등록번호`,
  c.`주소` AS `우편주소`,
  c.`주소` AS `주소`,
  c.`사업자주소` AS `사업자주소`,
  c.`판매구역` AS `판매구역`,
  c.`판매구역명` AS `판매구역명`,
  CAST(NULL AS STRING) AS `기존자재번호`,
  CAST(NULL AS STRING) AS `DIPS자재번호`,
  CAST(NULL AS STRING) AS `SG코드`,
  CAST(NULL AS STRING) AS `SG명`,
  CAST(NULL AS STRING) AS `SG상위코드`,
  CAST(NULL AS STRING) AS `SG상위명`,
  s.`update_date` AS `update_date`,
  s.`file_name` AS `file_name`
FROM h_hmfo_fsi.gd_rst_ing.sap_zsdr0008_sales_history_analysis_list_rst_ing_f s
LEFT JOIN cm c
  ON LPAD(CAST(s.`고객코드` AS STRING), 10, '0') = c.`고객코드10`
LEFT JOIN cm za
  ON LPAD(COALESCE(NULLIF(c.`ZA대표거래처`, ''), s.`고객코드`), 10, '0') = za.`고객코드10`
LEFT JOIN cm zb
  ON LPAD(COALESCE(NULLIF(c.`ZB본부`, ''), s.`고객코드`), 10, '0') = zb.`고객코드10`
LEFT JOIN cm zp
  ON LPAD(COALESCE(NULLIF(c.`ZP본사`, ''), s.`고객코드`), 10, '0') = zp.`고객코드10`
